MASK:
  INIT: '1s'
  SCALE: 1e-2
  THRESHOLD: 5e-3
  MASK_LOSS: True
  LOSS_WEIGHT: 1e-4
  MASK_MLP: False
  GDR: True
  GDR_LAMBDA: 1.

TEST:
  NO_TEST: True
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]
  RRCROP_SCALE: (0.5, 1.0)

OPTIM:
  NAME: "adam"
  WEIGHT_DECAY: 0.
  LR: 8e-5
  MAX_EPOCH: 30
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: -1

TRAIN:
  PRINT_FREQ: 5

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"